### ISSUE TITLE
Exception: AttributeError: 'NoneType' object has no attribute 'append'

### ISSUE THREAD

**Issue by tobp** [thorstenb/odpdown#21]
With the version offered via Python's "pip" (cf. #20) and a simple .odp file (open impress of LO 4.0.4 with "new", save it), it fails for `odpdown test.md Untitled.odp  out.odp` with the following exception.

Expected: An error message telling what went wrong.

    Traceback (most recent call last):
    File "$HOME/python/python/bin/odpdown", line 9, in <module>    main()
    File "$HOME/python/python/bin/odpdown", line 6, in main    odpdown.main()
    File "$HOME/python/python/lib/python2.7/site-packages/odpdown.py", line 853, in main
      highlight_style=args.highlight_style)
    File "$HOME/python/python/lib/python2.7/site-packages/odpdown.py", line 444, in __init__
      automatic=True)
    File "$HOME/python/python/lib/python2.7/site-packages/lpod/document.py", line 606, in insert_style
      container.append(style)
    AttributeError: 'NoneType' object has no attribute 'append'

**Comment by thorstenb** [comment]
Yeah, that's a bug in lpod-python. Pull request pending, https://github.com/lpod/lpod-python/pull/16 - sadly no reaction also on poking the authors directly. Use my fork for the while (see also requirements.txt).

**Comment by thorstenb** [comment]
Oh, actually I also patched the opensuse packages with that fix. No jurisdiction over the PyPI tarballs of course...
